---
deployment:
  tasks:
    - export DEPLOYPATH=/home/andrsipd/public_html/
    - /home/andrsipd/repositories/portfolio index.html $DEPLOYPATH
    - /home/andrsipd/repositories/portfolio main.js $DEPLOYPATH
    - /home/andrsipd/repositories/portfolio -R img $DEPLOYPATH
    - /home/andrsipd/repositories/portfolio -R js $DEPLOYPATH
    - /home/andrsipd/repositories/portfolio -R css $DEPLOYPATH
