---
deployment:
  tasks:
    - export DEPLOYPATH=/home/andrsipd/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp main.js $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH